import { describe, expect, it } from "vitest";
import JSZip from "jszip";

import { buildProofPackDelivery, createProofCaseFromQuestionnaire } from "@blackproof/core";
import { verifyDeliveryZip as verifyStandaloneDeliveryZip } from "@blackproof/verifier";
import { buildProofPackDeliveryZipBlob, buildProofPackZipBlob } from "./proofpack-zip";
import { verifyProofPackZipBlob } from "./proofpack-zip-verifier";

function asBlob(bytes: Uint8Array): Blob {
  return new Blob([bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer]);
}

function rewriteDeclaredExpandedSize(bytes: Uint8Array, filename: string, declaredSize: number): Uint8Array {
  const output = Uint8Array.from(bytes);
  const view = new DataView(output.buffer, output.byteOffset, output.byteLength);
  const decoder = new TextDecoder();
  let updates = 0;
  for (let offset = 0; offset + 30 <= output.byteLength; offset += 1) {
    const signature = view.getUint32(offset, true);
    if (signature === 0x04034b50) {
      const nameLength = view.getUint16(offset + 26, true);
      const name = decoder.decode(output.subarray(offset + 30, offset + 30 + nameLength));
      if (name === filename) {
        view.setUint32(offset + 22, declaredSize, true);
        updates += 1;
      }
    } else if (signature === 0x02014b50 && offset + 46 <= output.byteLength) {
      const nameLength = view.getUint16(offset + 28, true);
      const name = decoder.decode(output.subarray(offset + 46, offset + 46 + nameLength));
      if (name === filename) {
        view.setUint32(offset + 24, declaredSize, true);
        updates += 1;
      }
    }
  }
  expect(updates).toBe(2);
  return output;
}

describe("ProofPack ZIP defensive extraction", () => {
  it("accepts and binds the comment of a Master generated by BLACKPROOF", async () => {
    const { proofpack } = await createProofCaseFromQuestionnaire("1. Le MFA est-il activé ?");
    const result = await verifyProofPackZipBlob(await buildProofPackZipBlob(proofpack));
    expect(result.kind).toBe("master-zip");
    expect(result.isValid).toBe(true);
  });

  it("returns verified Delivery JSON from the same bounded extraction pass", async () => {
    const fixture = await createProofCaseFromQuestionnaire("1. Le MFA est-il activé pour les administrateurs ?");
    fixture.questions[0]!.answerText = "Le MFA est activé.";
    fixture.questions[0]!.answerExportStatus = "ready";
    const delivery = await buildProofPackDelivery(fixture.proofpack, {
      questionIds: [fixture.questions[0]!.id],
      evidenceIds: [],
      confirmed: true,
    });

    const blob = await buildProofPackDeliveryZipBlob(delivery);
    const result = await verifyProofPackZipBlob(blob);

    expect(result.kind).toBe("delivery-zip");
    if (result.kind !== "delivery-zip") throw new Error("Expected a Delivery ZIP result.");
    expect(result.isValid).toBe(true);
    expect(JSON.parse(result.deliveryJson ?? "null")).toMatchObject({ fingerprint: delivery.fingerprint });
    const standalone = await verifyStandaloneDeliveryZip(new Uint8Array(await blob.arrayBuffer()));
    expect(standalone.isValid).toBe(true);
    expect(standalone.validCanonicalSidecars).toBe(true);
  });

  it("rejects a supported-looking ZIP comment bound to another fingerprint", async () => {
    const { proofpack } = await createProofCaseFromQuestionnaire("1. Les sauvegardes sont-elles testées ?");
    const bytes = new Uint8Array(await (await buildProofPackZipBlob(proofpack)).arrayBuffer());
    bytes[bytes.length - 1] = bytes[bytes.length - 1] === 0x61 ? 0x62 : 0x61;
    await expect(verifyProofPackZipBlob(asBlob(bytes))).rejects.toMatchObject({ code: "PROOFPACK_ZIP_INVALID" });
  });

  it("rejects declared expansion over budget before materializing files", async () => {
    const zip = new JSZip();
    zip.file("manifest.json", "A".repeat(21_000_000));
    const bytes = await zip.generateAsync({ type: "uint8array", compression: "DEFLATE", compressionOptions: { level: 9 } });
    expect(bytes.byteLength).toBeLessThan(100_000);

    await expect(verifyProofPackZipBlob(asBlob(bytes))).rejects.toMatchObject({
      code: "PROOFPACK_ZIP_FILE_TOO_LARGE",
    });
  });

  it("rejects payload bytes that do not match the authenticated CRC", async () => {
    const zip = new JSZip();
    zip.file("manifest.json", JSON.stringify({ manifestVersion: "invalid-fixture" }));
    const bytes = await zip.generateAsync({ type: "uint8array", compression: "STORE" });
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    const nameLength = view.getUint16(26, true);
    const extraLength = view.getUint16(28, true);
    bytes[30 + nameLength + extraLength] ^= 0x01;

    await expect(verifyProofPackZipBlob(asBlob(bytes))).rejects.toMatchObject({
      code: "PROOFPACK_ZIP_INVALID",
    });
  });

  it("rejects runtime expansion that differs from validated ZIP metadata", async () => {
    const zip = new JSZip();
    zip.file("manifest.json", "A".repeat(1_024));
    const bytes = await zip.generateAsync({ type: "uint8array", compression: "DEFLATE" });
    const inconsistent = rewriteDeclaredExpandedSize(bytes, "manifest.json", 1_023);

    await expect(verifyProofPackZipBlob(asBlob(inconsistent))).rejects.toMatchObject({
      code: "PROOFPACK_ZIP_INVALID",
    });
  });
});
